/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package blood.bank.management.system;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class DisplayBlood extends javax.swing.JFrame {

    Hospital Hospital1 = new Hospital("Selangor", "Selayang Hospital               ", "Public ", new BloodBank());
    Hospital Hospital2 = new Hospital("Selangor", "Pusrawi Hospital               ", "Public ", new BloodBank());
    Hospital Hospital3 = new Hospital("Selangor", "Banting Hospital", "Private", new BloodBank());
    Hospital Hospital4 = new Hospital("Penang   ", "Island Hospital              ", "Private ", new BloodBank());
    Hospital Hospital5 = new Hospital("Johor   ", "Columbia Asia Hospital        ", "Private", new BloodBank());
    Hospital Hospital6 = new Hospital("Selangor  ", "KPJ Kajang Specialist Hospital     ", "Public", new BloodBank());
    
    /**
     * Creates new form DisplayBlood
     */
    public DisplayBlood() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnDisplay = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        labelHospital = new javax.swing.JLabel();
        labelHospital1 = new javax.swing.JLabel();
        labelHospital2 = new javax.swing.JLabel();
        labelHospital3 = new javax.swing.JLabel();
        labelHospital4 = new javax.swing.JLabel();
        labelHospital5 = new javax.swing.JLabel();
        labelHospital6 = new javax.swing.JLabel();
        inputHospitalNo1 = new javax.swing.JLabel();
        labelBloodGroup = new javax.swing.JLabel();
        txtHospital = new javax.swing.JTextField();
        inputBloodGroup = new javax.swing.JLabel();
        txtBloodGroup = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lblHospital = new javax.swing.JLabel();
        lblDonor = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        jLabel1.setText("Display Blood");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 21, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 91, 787, 10));

        btnDisplay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Details.png"))); // NOI18N
        btnDisplay.setText("Display");
        btnDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayActionPerformed(evt);
            }
        });
        getContentPane().add(btnDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 107, 97, 32));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Logout.png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(689, 36, 92, 32));

        labelHospital.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelHospital.setText("LIST OF HOSPITAL                                         STATE                                               SECTOR");
        getContentPane().add(labelHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 151, 642, 32));

        labelHospital1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelHospital1.setText("...");
        getContentPane().add(labelHospital1, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 189, 642, 32));

        labelHospital2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelHospital2.setText("...");
        getContentPane().add(labelHospital2, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 227, 642, 32));

        labelHospital3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelHospital3.setText("...");
        getContentPane().add(labelHospital3, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 265, 642, 32));

        labelHospital4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelHospital4.setText("...");
        getContentPane().add(labelHospital4, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 303, 642, 32));

        labelHospital5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelHospital5.setText("...");
        getContentPane().add(labelHospital5, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 341, 642, 32));

        labelHospital6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelHospital6.setText("...");
        getContentPane().add(labelHospital6, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 379, 642, 32));

        inputHospitalNo1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        inputHospitalNo1.setText("Search hospital no: ");
        getContentPane().add(inputHospitalNo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 423, -1, 41));

        labelBloodGroup.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        labelBloodGroup.setText("Blood Group: [A+/ O+/ B+/ AB+/ A-/ O-/ B-/ AB-]");
        getContentPane().add(labelBloodGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 476, 642, 32));

        txtHospital.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHospitalActionPerformed(evt);
            }
        });
        getContentPane().add(txtHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 433, 160, -1));

        inputBloodGroup.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        inputBloodGroup.setText("Search blood group: ");
        getContentPane().add(inputBloodGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 514, -1, 38));

        txtBloodGroup.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txtBloodGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 525, 159, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "List of Donors", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 0, 51))); // NOI18N

        lblHospital.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblHospital.setText("Hospital:");

        lblDonor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDonor.setText("1)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDonor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblHospital, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(527, 527, 527))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDonor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 571, -1, -1));

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search1.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 522, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/FcxA0Q.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 770));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHospitalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHospitalActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed

        User donor1 = new Donor("mary", "stethometer", "Fatimah", "F", 98, 24.1f, "A+", Hospital1, 2, 1, 12);
        User donor2 = new Donor("izz", "windbound", "Luqman", "M", 84, 68.1f, "O+", Hospital1, 2, 1, 12);
        User donor3 = new Donor("shaz", "materteral", "Teow Fei", "F", 67, 45.1f, "B+", Hospital1, 2, 1, 12);
        User donor4 = new Donor("carr", "muciferous", "Lois David", "F", 76, 75.1f, "AB+", Hospital1, 2, 1, 12);
        User donor5 = new Donor("letchum", "vespertilian", "Nalla", "F", 66, 45.1f, "A-", Hospital1, 2, 1, 12);
        User donor6 = new Donor("tehah", "ontography", "Zakharia Chan", "F", 67, 45.1f, "O-", Hospital1, 2, 1, 12);
        User donor7 = new Donor("hender", "killock", "Sten Lee", "M", 47, 45.1f, "B-", Hospital1, 2, 1, 12);
        User donor8 = new Donor("teresa", "hypolimnion", "Hasine Miku", "F", 76, 45.1f, "AB-", Hospital1, 2, 1, 12);

        if(txtHospital.getText().equals("1")){
            lblHospital.setText("Hospital: " +Hospital1.getName());}
        else if(txtHospital.getText().equals("2")){
            lblHospital.setText("Hospital: " +Hospital2.getName());}
        else if(txtHospital.getText().equals("3")){
            lblHospital.setText("Hospital: " +Hospital3.getName());}
        else if(txtHospital.getText().equals("4")){
            lblHospital.setText("Hospital: " +Hospital4.getName());}
        else if(txtHospital.getText().equals("5")){
            lblHospital.setText("Hospital: " +Hospital5.getName());}
        else if(txtHospital.getText().equals("6")){
            lblHospital.setText("Hospital: " +Hospital6.getName());}
        else{
            lblHospital.setText("Hospital: No hospital found!");}

        if(txtBloodGroup.getText().equals("A+")){
            lblDonor.setText("1) " +donor1.getName());}
        else if(txtBloodGroup.getText().equals("O+")){
            lblDonor.setText("1) " +donor2.getName());}
        else if(txtBloodGroup.getText().equals("B+")){
            lblDonor.setText("1) " +donor3.getName());}
        else if(txtBloodGroup.getText().equals("AB+")){
            lblDonor.setText("1) " +donor4.getName());}
        else if(txtBloodGroup.getText().equals("A-")){
            lblDonor.setText("1) " +donor5.getName());}
        else if(txtBloodGroup.getText().equals("O-")){
            lblDonor.setText("1) " +donor6.getName());}
        else if(txtBloodGroup.getText().equals("B-")){
            lblDonor.setText("1) " +donor7.getName());}
        else if(txtBloodGroup.getText().equals("AB-")){
            lblDonor.setText("1) " +donor8.getName());}

    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayActionPerformed
        // TODO add your handling code here:
        
        if(btnDisplay.getText()=="Display"){
            labelHospital1.setText("1. " +Hospital1.getName() +"                        " +Hospital1.getState() +"                                              " +Hospital1.getSector());
            labelHospital2.setText("2. " +Hospital2.getName() +"                          " +Hospital2.getState() +"                                              " +Hospital2.getSector());
            labelHospital3.setText("3. " +Hospital3.getName() +"                                         " +Hospital3.getState() +"                                             "+Hospital3.getSector());
            labelHospital4.setText("4. " +Hospital4.getName() +"                              " +Hospital4.getState() +"                                            " +Hospital4.getSector());
            labelHospital5.setText("5. " +Hospital5.getName() +"                       " +Hospital5.getState() +"                                               " +Hospital5.getSector());
            labelHospital6.setText("6. " +Hospital6.getName() +"             " +Hospital6.getState() +"                                            " +Hospital6.getSector());
            btnDisplay.setText("Hide");
        }else if(btnDisplay.getText()=="Hide"){
            labelHospital1.setText("...");
            labelHospital2.setText("...");
            labelHospital3.setText("...");
            labelHospital4.setText("...");
            labelHospital5.setText("...");
            labelHospital6.setText("...");
            btnDisplay.setText("Display");
        }
    }//GEN-LAST:event_btnDisplayActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new menu().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayBlood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayBlood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayBlood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayBlood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayBlood().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDisplay;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel inputBloodGroup;
    private javax.swing.JLabel inputHospitalNo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelBloodGroup;
    private javax.swing.JLabel labelHospital;
    private javax.swing.JLabel labelHospital1;
    private javax.swing.JLabel labelHospital2;
    private javax.swing.JLabel labelHospital3;
    private javax.swing.JLabel labelHospital4;
    private javax.swing.JLabel labelHospital5;
    private javax.swing.JLabel labelHospital6;
    private javax.swing.JLabel lblDonor;
    private javax.swing.JLabel lblHospital;
    private javax.swing.JTextField txtBloodGroup;
    private javax.swing.JTextField txtHospital;
    // End of variables declaration//GEN-END:variables
}
